# Generated by Django 3.2.15 on 2022-09-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='番地など'),
        ),
        migrations.AddField(
            model_name='place',
            name='address1',
            field=models.CharField(max_length=500, null=True, verbose_name='address1'),
        ),
        migrations.AddField(
            model_name='place',
            name='address2',
            field=models.CharField(max_length=500, null=True, verbose_name='address2'),
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city', verbose_name='市町村'),
        ),
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='place',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='place',
            name='prefecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.prefecture', verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='place',
            name='time_frame',
            field=models.IntegerField(choices=[(15, 'Quarter'), (30, 'Half'), (45, 'Three Quarter'), (60, 'Hour')], default=60),
        ),
    ]
