# Generated by Django 3.2.15 on 2022-09-15 00:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20220912_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, verbose_name='Place Item')),
                ('price_per_time_frame', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='時間枠あたりの料金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_item', to='hosts.place', verbose_name='場所')),
            ],
            options={
                'db_table': 'place_items',
            },
        ),
    ]
