# Generated by Django 3.2.15 on 2022-09-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Region Name')),
                ('name_kana', models.CharField(max_length=50, verbose_name='Region Name Kana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=2, null=True, verbose_name='都道府県コード')),
                ('name', models.CharField(max_length=255, verbose_name='地方名')),
                ('name_kana', models.CharField(max_length=255, verbose_name='地方名かな')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.region', verbose_name='エリア地方 id')),
            ],
            options={
                'db_table': 'prefecture',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='団体コード')),
                ('name', models.CharField(max_length=60, verbose_name='市区町村 name')),
                ('name_kana', models.CharField(max_length=200, verbose_name='市区町村 かな')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.prefecture', verbose_name='都道府県 id')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=500, verbose_name='address1')),
                ('address2', models.CharField(max_length=500, verbose_name='address2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.city', verbose_name='City id')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
