# Generated by Django 3.2.15 on 2022-09-15 04:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0003_placeitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField(blank=True, null=True, verbose_name='予約開始時間')),
                ('end_date_time', models.DateTimeField(blank=True, null=True, verbose_name='予約終了時間')),
                ('num_time_frame', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='時間枠数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hosts.place', verbose_name='場所')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='予約したユーザー')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5.0)])),
                ('body', models.CharField(max_length=600, verbose_name='Review Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='予約ID')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TEMPORARY', 'Temporary'), ('APPROVAL', 'Approval'), ('REFUSE', 'Refuse')], default='APPROVAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_status', to='bookings.booking', verbose_name='予約ID')),
            ],
            options={
                'db_table': 'booking_status',
            },
        ),
        migrations.CreateModel(
            name='BookingPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_price', to='bookings.booking', verbose_name='予約ID')),
            ],
            options={
                'db_table': 'booking_price',
            },
        ),
        migrations.CreateModel(
            name='BookingCheckOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout', models.DateTimeField(verbose_name='当日のチェックアウト')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_checkout', to='bookings.booking', verbose_name='予約ID')),
            ],
            options={
                'db_table': 'booking_checkout',
            },
        ),
        migrations.CreateModel(
            name='BookingCheckIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin', models.DateTimeField(verbose_name='入店時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_checkin', to='bookings.booking', verbose_name='予約ID')),
            ],
            options={
                'db_table': 'booking_checkin',
            },
        ),
    ]
